version: '3.6'

services:

  # Backend API
  buckeye-charge-api:
    build: ./
    command: npm start
    working_dir: /usr/src/buckeye-charge-api
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/buckeye-charge-docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/buckeye-charge-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buckeye-charge-docker
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./buckeye-charge.sql:/docker-entrypoint-initdb.d/buckeye-charge.sql
    