version: '3.6'

services:

  # Backend API
  buckeye-charge-api:
    container_name: back-end
    build: ./
    command: npm start
    working_dir: /usr/src/buckeye-charge-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/buckeye-charge-api
  
  # Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"